import type { Metadata } from "next";
import { Inter, Roboto, } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
const inter =Roboto({ subsets: ["latin"] ,weight:"400"});
import { cn } from "@/lib/utils";
import Providers from "@/lib/LoadingProvider";
export const metadata: Metadata = {
  title: "National Id Registration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("max-w-screen bg-black",inter.className)}>
        {/* <Header/> */}
        <main>
          <Providers>
          {children}
          </Providers>
         
          
       
        </main>
        <Toaster />
      </body>
    </html>
  );
}
